
CREATE TABLE `cm_year_campus` (
  `YEAR_CAMPUS_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `YEAR` int(4) NOT NULL,
  `CAMPUS_CODE` varchar(4) NOT NULL,
  PRIMARY KEY (`YEAR_CAMPUS_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;


CREATE TABLE `cm_lecturer` (
  `LECTURER_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `YEAR_CAMPUS_F_ID` bigint(20) NOT NULL,
  `USERNAME` varchar(64) NOT NULL,
  PRIMARY KEY (`LECTURER_ID`),
  KEY `FK_YEAR_CAMPUS_F_ID` (`YEAR_CAMPUS_F_ID`),
  CONSTRAINT `FK_YEAR_CAMPUS_F_ID` FOREIGN KEY (`YEAR_CAMPUS_F_ID`) REFERENCES `cm_year_campus` (`YEAR_CAMPUS_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;


CREATE TABLE `cm_modules` (
  `MODULE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `LECTURER_F_ID` bigint(20) NOT NULL,
  `COURSE_CODE` varchar(16) NOT NULL,
  `COURSE_LEVEL` varchar(8) NOT NULL,
  `COURSE_MODULE` varchar(8) NOT NULL,
  `STATUS` varchar(32) NOT NULL,
  `METHOD_OF_DEL` varchar(64) DEFAULT NULL,
  `PRESENT_CAT` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`MODULE_ID`),
  KEY `FK_LECTURER_F_ID` (`LECTURER_F_ID`),
  CONSTRAINT `FK_LECTURER_F_ID` FOREIGN KEY (`LECTURER_F_ID`) REFERENCES `cm_lecturer` (`LECTURER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8;

