
package za.ac.nwu.wsdl.studentacademicregistration;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "InvalidParameterException", targetNamespace = "http://nwu.ac.za/wsdl/StudentAcademicRegistration")
public class InvalidParameterException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidParameterException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InvalidParameterException_Exception(String message, InvalidParameterException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InvalidParameterException_Exception(String message, InvalidParameterException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: za.ac.nwu.wsdl.studentacademicregistration.InvalidParameterException
     */
    public InvalidParameterException getFaultInfo() {
        return faultInfo;
    }

}
