
package za.ac.nwu.wsdl.studentacademicregistration;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "StudentAcademicRegistrationService", targetNamespace = "http://nwu.ac.za/wsdl/StudentAcademicRegistration", wsdlLocation = "/CourseOfferingService.wsdl")
public class StudentAcademicRegistrationService_Service
    extends Service
{

    private final static URL STUDENTACADEMICREGISTRATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException STUDENTACADEMICREGISTRATIONSERVICE_EXCEPTION;
    private final static QName STUDENTACADEMICREGISTRATIONSERVICE_QNAME = new QName("http://nwu.ac.za/wsdl/StudentAcademicRegistration", "StudentAcademicRegistrationService");

    static {
        STUDENTACADEMICREGISTRATIONSERVICE_WSDL_LOCATION = za.ac.nwu.wsdl.studentacademicregistration.StudentAcademicRegistrationService_Service.class.getResource("/CourseOfferingService.wsdl");
        WebServiceException e = null;
        if (STUDENTACADEMICREGISTRATIONSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/CourseOfferingService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        STUDENTACADEMICREGISTRATIONSERVICE_EXCEPTION = e;
    }

    public StudentAcademicRegistrationService_Service() {
        super(__getWsdlLocation(), STUDENTACADEMICREGISTRATIONSERVICE_QNAME);
    }

    public StudentAcademicRegistrationService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTACADEMICREGISTRATIONSERVICE_QNAME, features);
    }

    public StudentAcademicRegistrationService_Service(URL wsdlLocation) {
        super(wsdlLocation, STUDENTACADEMICREGISTRATIONSERVICE_QNAME);
    }

    public StudentAcademicRegistrationService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTACADEMICREGISTRATIONSERVICE_QNAME, features);
    }

    public StudentAcademicRegistrationService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentAcademicRegistrationService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentAcademicRegistrationService
     */
    @WebEndpoint(name = "StudentAcademicRegistrationServicePort")
    public StudentAcademicRegistrationService getStudentAcademicRegistrationServicePort() {
        return super.getPort(new QName("http://nwu.ac.za/wsdl/StudentAcademicRegistration", "StudentAcademicRegistrationServicePort"), StudentAcademicRegistrationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentAcademicRegistrationService
     */
    @WebEndpoint(name = "StudentAcademicRegistrationServicePort")
    public StudentAcademicRegistrationService getStudentAcademicRegistrationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://nwu.ac.za/wsdl/StudentAcademicRegistration", "StudentAcademicRegistrationServicePort"), StudentAcademicRegistrationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTACADEMICREGISTRATIONSERVICE_EXCEPTION!= null) {
            throw STUDENTACADEMICREGISTRATIONSERVICE_EXCEPTION;
        }
        return STUDENTACADEMICREGISTRATIONSERVICE_WSDL_LOCATION;
    }

}
