
package za.ac.nwu.wsdl.courseoffering;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "MissingParameterException", targetNamespace = "http://nwu.ac.za/wsdl/CourseOffering")
public class MissingParameterException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MissingParameterException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public MissingParameterException_Exception(String message, MissingParameterException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public MissingParameterException_Exception(String message, MissingParameterException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: za.ac.nwu.wsdl.courseoffering.MissingParameterException
     */
    public MissingParameterException getFaultInfo() {
        return faultInfo;
    }

}
